export const GET_COURSES = "GET_COURSES";
export const GET_SINGLE_COURSE = "GET_SINGLE_COURSE";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CAREER_RELATED_COURSES = "GET_CAREER_RELATED_COURSES";